import type { GuideContent } from './types';

export const guideEn: GuideContent = {
  heroTitle: 'Budgerigar Care Guide',
  heroSubtitle:
    'Everything you need to keep your Australian budgie happy, healthy, and thriving. Backed by avian veterinary science.',

  sections: [
    {
      id: 'species',
      icon: '\u{1F99C}',
      title: 'Know Your Budgie',
      summary:
        'Australian budgerigars (Melopsittacus undulatus) are intelligent, social parrots with complex vocal communication.',
      bullets: [
        'Lifespan: 7-15 years with proper care; up to 20 in exceptional cases.',
        'Weight: healthy range is 30-40 grams. Daily fluctuations of 1-2g are normal.',
        'Social: flock birds — they need at least 2 hours of interaction daily.',
        'Vocal range: 1-8 kHz. They can learn up to 100+ words.',
        'Intelligence: comparable to a 2-year-old human in problem-solving.',
      ],
      tone: 'info',
    },
    {
      id: 'habitat',
      icon: '\u{1F3E0}',
      title: 'Ideal Habitat Setup',
      summary: 'The cage environment directly impacts health, mood, and vocalization patterns.',
      bullets: [
        'Minimum cage size: 18"x18"x24" for one budgie, larger for pairs.',
        'Place at eye level in a quiet room with natural light (not direct sun).',
        'Ideal temperature: 65-80\u00B0F (18-27\u00B0C). Never below 60\u00B0F or above 85\u00B0F.',
        'Humidity: 40-70%. Use a hygrometer to monitor.',
        'Avoid: kitchen (fumes), drafty windows, near AC/heaters.',
        'Cover the cage at night for 10-12 hours of uninterrupted sleep.',
      ],
      tone: 'tip',
    },
    {
      id: 'nutrition',
      icon: '\u{1F966}',
      title: 'Nutrition Essentials',
      summary: 'Seed-only diets cause malnutrition. A varied diet is critical for longevity.',
      bullets: [
        'Base: high-quality pellets should be 60-70% of diet.',
        'Fresh veggies daily: dark leafy greens, carrots, broccoli, sweet potato.',
        'Safe fruits (small amounts): apple, berries, melon, banana. No avocado.',
        'Seeds: treat only, max 20% of diet. Millet sprays for training/bonding.',
        'Cuttlebone or mineral block for calcium. Fresh water changed twice daily.',
        'TOXIC foods: avocado, chocolate, caffeine, onion, garlic, alcohol.',
      ],
      tone: 'tip',
    },
    {
      id: 'daily_care',
      icon: '\u{2705}',
      title: 'Daily Care Routine',
      summary: 'Consistency reduces stress and makes health changes easier to spot.',
      bullets: [
        'Morning: uncover, fresh food + water, 5 min visual health check.',
        'Midday: social interaction, out-of-cage time if safe, enrichment rotation.',
        'Evening: dim lights gradually, cover cage at consistent time.',
        'Weekly: deep cage clean, toy rotation, weigh each bird, trim nails if needed.',
        'Monthly: check cere condition, beak length, feather quality, vent area.',
      ],
      tone: 'tip',
    },
    {
      id: 'behavior',
      icon: '\u{1F9E0}',
      title: 'Behavior Decoder',
      summary: 'Understanding body language helps you catch problems early.',
      bullets: [
        'Fluffed + eyes closed during day = feels cold or unwell (not sleeping).',
        'Head bobbing = happy, seeking attention, or feeding behavior.',
        'Beak grinding = relaxed, content, usually before sleep (GOOD sign).',
        'Tail bobbing while breathing = respiratory distress (URGENT).',
        'Wing flipping = stretching (normal) vs. repeated = irritation/pain.',
        'One foot tucked = comfortable. Both feet gripping tight = scared/tense.',
        'Regurgitation toward you = bonding. Vomiting (head shaking) = illness.',
      ],
      tone: 'info',
    },
    {
      id: 'risks',
      icon: '\u{26A0}',
      title: 'Top Health Risks',
      summary: 'Prevention is far cheaper and more effective than treatment.',
      bullets: [
        'Respiratory: Teflon/PTFE fumes, scented candles, air fresheners, smoke.',
        'Crop issues: from spoiled soft food left too long (>4 hours).',
        'Fatty liver disease: from seed-only diet + lack of exercise.',
        'Psittacosis: bacterial infection transmissible to humans. Quarantine new birds.',
        'Mites: scaly face mites appear as crusty buildup around beak/cere.',
        'Megabacteria (AGY): yeast infection causing weight loss despite eating.',
      ],
      tone: 'risk',
    },
    {
      id: 'enrichment',
      icon: '\u{1F3B2}',
      title: 'Enrichment & Mental Health',
      summary: 'Boredom causes feather plucking, screaming, and depression.',
      bullets: [
        'Rotate toys every 3-4 days to maintain novelty.',
        'Foraging toys: wrap treats in paper, hide seeds in crinkled cupcake liners.',
        'Training: budgies learn tricks fast. Use positive reinforcement + millet.',
        'Music: many budgies enjoy soft music. Avoid sudden loud sounds.',
        'Mirror use: okay for single birds short-term, but can cause hormonal issues.',
        'Out-of-cage time: bird-proof the room. No ceiling fans, open windows, or toxic plants.',
      ],
      tone: 'tip',
    },
  ],

  vocalizationGuide: {
    title: 'Vocalization Reference',
    subtitle: 'What each sound means and when to pay attention.',
    items: [
      {
        id: 'singing',
        name: 'Singing / Warbling',
        icon: '\u{1F3B6}',
        description: 'Complex melodic sequences with frequency modulation.',
        sound: 'Continuous, varied pitch patterns lasting 5-30 seconds.',
        mood: 'Happy, content, socially engaged.',
        action: 'Great sign! Your budgie is comfortable and thriving.',
      },
      {
        id: 'chattering',
        name: 'Chattering',
        icon: '\u{1F4AC}',
        description: 'Rapid, repetitive short vocalizations.',
        sound: 'Quick, rhythmic bursts at moderate volume.',
        mood: 'Active, social, communicating.',
        action: 'Normal flock behavior. They may be "talking" to you or practicing speech.',
      },
      {
        id: 'contact_call',
        name: 'Contact Call',
        icon: '\u{1F4E2}',
        description: 'Brief, tonal chirp to locate flock members.',
        sound: 'Single short chirp, 2-4 kHz, repeated every few seconds.',
        mood: 'Seeking connection, mild anxiety if unanswered.',
        action: 'Respond with a whistle or call back. They need to know you are there.',
      },
      {
        id: 'alarm',
        name: 'Alarm Call',
        icon: '\u{1F6A8}',
        description: 'Loud, sharp, broadband screech.',
        sound: 'Harsh, high-pitched, startling. May repeat rapidly.',
        mood: 'Frightened, perceiving threat.',
        action: 'Check for threats: predators, shadows, sudden movements, unfamiliar objects.',
      },
      {
        id: 'distress',
        name: 'Distress Call',
        icon: '\u{1F198}',
        description: 'Irregular, urgent vocalizations with high energy.',
        sound: 'Variable pitch, high volume, agitated pattern.',
        mood: 'Pain, extreme stress, or physical discomfort.',
        action: 'Inspect immediately. Check for injuries, entanglement, or illness signs.',
      },
      {
        id: 'beak_grinding',
        name: 'Beak Grinding',
        icon: '\u{1F634}',
        description: 'Rhythmic, soft grinding sound from the beak.',
        sound: 'Low amplitude, 10-20 Hz rhythm, barely audible.',
        mood: 'Deeply relaxed, sleepy, content.',
        action: 'Excellent sign! Your budgie feels safe. Usually heard at bedtime.',
      },
      {
        id: 'silence',
        name: 'Prolonged Silence',
        icon: '\u{1F910}',
        description: 'Absence of vocalizations for extended periods.',
        sound: 'No vocalization during normally active hours.',
        mood: 'May indicate illness, fear, or depression.',
        action: 'If lasting >2 hours during active time, check health signs. Consult vet if combined with other symptoms.',
      },
    ],
  },

  healthChecklist: {
    title: 'Quick Health Check',
    subtitle: 'Run through this checklist during your daily observation.',
    items: [
      {
        id: 'eyes',
        icon: '\u{1F441}',
        label: 'Eyes',
        healthy: 'Bright, clear, alert, equally dilated.',
        warning: 'Swollen, crusty, discharge, half-closed during day.',
      },
      {
        id: 'cere',
        icon: '\u{1F535}',
        label: 'Cere (nose)',
        healthy: 'Smooth, consistent color (blue=male, brown/tan=female).',
        warning: 'Crusty, flaky, discolored, or swollen.',
      },
      {
        id: 'feathers',
        icon: '\u{1FAB6}',
        label: 'Feathers',
        healthy: 'Smooth, sleek, well-groomed. Normal molting is gradual.',
        warning: 'Fluffed constantly, bald patches, stress bars, broken shafts.',
      },
      {
        id: 'breathing',
        icon: '\u{1F4A8}',
        label: 'Breathing',
        healthy: 'Quiet, no visible effort, tail still.',
        warning: 'Open-mouth breathing, tail bobbing, clicking/wheezing sounds.',
      },
      {
        id: 'droppings',
        icon: '\u{1F4A9}',
        label: 'Droppings',
        healthy: 'Green/white, firm, consistent. 40-50 per day is normal.',
        warning: 'Watery, discolored (yellow/black/red), undigested seeds.',
      },
      {
        id: 'posture',
        icon: '\u{1F9CD}',
        label: 'Posture',
        healthy: 'Upright, active, one foot tucked when resting.',
        warning: 'Sitting on cage floor, hunched, puffed up during day.',
      },
      {
        id: 'appetite',
        icon: '\u{1F37D}',
        label: 'Appetite',
        healthy: 'Eating regularly, active at food dish, cracking seeds.',
        warning: 'Sitting at dish but not eating, weight loss, food untouched.',
      },
    ],
  },

  emergencySigns: {
    title: 'Emergency: See a Vet Immediately',
    subtitle: 'These signs require urgent avian veterinary attention.',
    signs: [
      'Sitting on the cage floor, fluffed up, eyes closed.',
      'Bleeding that does not stop within 5 minutes.',
      'Open-mouth breathing or persistent tail bobbing.',
      'Seizures, loss of balance, or inability to perch.',
      'Vomiting (head shaking + regurgitation on chest feathers).',
      'Sudden swelling anywhere on the body.',
      'No droppings for 12+ hours.',
      'Ingestion of toxic substance (Teflon fumes, chocolate, avocado).',
    ],
    action:
      'Keep the bird warm (85\u00B0F / 29\u00B0C), in a quiet dark space, and transport to an avian vet ASAP. Do not attempt home treatment for these symptoms.',
  },

  howToTitle: 'How to Use This App Effectively',
  howToSteps: [
    '1. Add each budgie\'s profile with name, photo, and notes about their personality.',
    '2. Record at least 30 seconds of audio in a quiet room with your phone near the cage.',
    '3. Review the AI analysis: mood, vocalization type, confidence, and probability breakdown.',
    '4. Check the bird detection badge \u2014 if your bird was not detected, try a quieter environment.',
    '5. Track trends weekly in History. One bad reading does not mean trouble \u2014 look for patterns.',
    '6. Set up habitat coordinates in Settings for weather and air quality context alerts.',
    '7. Use this Guide as a reference whenever you notice behavioral changes.',
  ],

  safetyNote:
    'This app provides AI-powered wellness monitoring and educational content. It does NOT replace professional diagnosis by a qualified avian veterinarian. When in doubt, always consult a vet.',
};
