import type { GuideContent } from './types';

export const guideEs: GuideContent = {
  heroTitle: 'Guia Completa del Periquito',
  heroSubtitle:
    'Todo lo que necesitas para mantener a tu periquito australiano feliz, sano y activo. Basado en ciencia veterinaria aviar.',

  sections: [
    {
      id: 'species',
      icon: '\u{1F99C}',
      title: 'Conoce a Tu Periquito',
      summary:
        'Los periquitos australianos (Melopsittacus undulatus) son loros inteligentes y sociales con comunicacion vocal compleja.',
      bullets: [
        'Esperanza de vida: 7-15 anos con buen cuidado; hasta 20 en casos excepcionales.',
        'Peso: rango saludable 30-40 gramos. Fluctuaciones de 1-2g al dia son normales.',
        'Sociales: aves de bandada \u2014 necesitan al menos 2 horas de interaccion diaria.',
        'Rango vocal: 1-8 kHz. Pueden aprender mas de 100 palabras.',
        'Inteligencia: comparable a un nino de 2 anos en resolucion de problemas.',
      ],
      tone: 'info',
    },
    {
      id: 'habitat',
      icon: '\u{1F3E0}',
      title: 'Habitat Ideal',
      summary: 'El entorno de la jaula impacta directamente la salud, animo y vocalizaciones.',
      bullets: [
        'Tamano minimo de jaula: 45x45x60 cm para un periquito, mas grande para parejas.',
        'Colocar a la altura de los ojos en un cuarto tranquilo con luz natural (no sol directo).',
        'Temperatura ideal: 18-27\u00B0C. Nunca debajo de 15\u00B0C ni arriba de 30\u00B0C.',
        'Humedad: 40-70%. Usa un higrometro para monitorear.',
        'Evitar: cocina (vapores), ventanas con corriente, cerca de AC/calefactores.',
        'Cubrir la jaula por la noche para 10-12 horas de sueno ininterrumpido.',
      ],
      tone: 'tip',
    },
    {
      id: 'nutrition',
      icon: '\u{1F966}',
      title: 'Nutricion Esencial',
      summary: 'Dietas solo de semillas causan desnutricion. Una dieta variada es critica.',
      bullets: [
        'Base: pellets de alta calidad deben ser 60-70% de la dieta.',
        'Verduras frescas diarias: hojas verdes oscuras, zanahoria, brocoli, camote.',
        'Frutas seguras (pequenas cantidades): manzana, moras, melon, platano. NUNCA aguacate.',
        'Semillas: solo como premio, maximo 20% de dieta. Mijo para entrenamiento.',
        'Jibia o bloque mineral para calcio. Agua fresca cambiada 2 veces al dia.',
        'TOXICO: aguacate, chocolate, cafeina, cebolla, ajo, alcohol.',
      ],
      tone: 'tip',
    },
    {
      id: 'daily_care',
      icon: '\u{2705}',
      title: 'Rutina Diaria de Cuidado',
      summary: 'La consistencia reduce estres y facilita detectar cambios de salud.',
      bullets: [
        'Manana: descubrir, comida + agua fresca, 5 min de revision visual.',
        'Mediodia: interaccion social, tiempo fuera de jaula si es seguro, rotar enriquecimiento.',
        'Noche: atenuar luces gradualmente, cubrir la jaula a hora consistente.',
        'Semanal: limpieza profunda, rotar juguetes, pesar cada ave, cortar unas si es necesario.',
        'Mensual: revisar cera, largo del pico, calidad de plumas, area de la cloaca.',
      ],
      tone: 'tip',
    },
    {
      id: 'behavior',
      icon: '\u{1F9E0}',
      title: 'Decodificador de Conducta',
      summary: 'Entender el lenguaje corporal ayuda a detectar problemas temprano.',
      bullets: [
        'Plumas erizadas + ojos cerrados de dia = frio o enfermo (no esta durmiendo).',
        'Cabeceo = feliz, buscando atencion o comportamiento de alimentacion.',
        'Rechinar de pico = relajado, contento, generalmente antes de dormir (BUENA senal).',
        'Cola moviendose al respirar = dificultad respiratoria (URGENTE).',
        'Aleteo = estiramiento (normal) vs. repetido = irritacion/dolor.',
        'Una pata recogida = comodo. Ambas patas agarrando fuerte = asustado/tenso.',
        'Regurgitacion hacia ti = vinculo. Vomito (sacudiendo cabeza) = enfermedad.',
      ],
      tone: 'info',
    },
    {
      id: 'risks',
      icon: '\u{26A0}',
      title: 'Principales Riesgos de Salud',
      summary: 'La prevencion es mucho mas barata y efectiva que el tratamiento.',
      bullets: [
        'Respiratorio: vapores de Teflon/PTFE, velas aromaticas, aromatizantes, humo.',
        'Problemas de buche: por comida blanda dejada demasiado tiempo (>4 horas).',
        'Higado graso: por dieta solo de semillas + falta de ejercicio.',
        'Psitacosis: infeccion bacteriana transmisible a humanos. Cuarentena aves nuevas.',
        'Acaros: los acaros de cara escamosa aparecen como costra alrededor del pico/cera.',
        'Megabacteria (AGY): infeccion por levadura que causa perdida de peso pese a comer.',
      ],
      tone: 'risk',
    },
    {
      id: 'enrichment',
      icon: '\u{1F3B2}',
      title: 'Enriquecimiento y Salud Mental',
      summary: 'El aburrimiento causa arrancado de plumas, gritos y depresion.',
      bullets: [
        'Rotar juguetes cada 3-4 dias para mantener novedad.',
        'Juguetes de forrajeo: envolver premios en papel, esconder semillas en moldes.',
        'Entrenamiento: los periquitos aprenden trucos rapido. Usa refuerzo positivo + mijo.',
        'Musica: muchos periquitos disfrutan musica suave. Evitar sonidos fuertes subitos.',
        'Espejos: ok para aves solas a corto plazo, pero pueden causar problemas hormonales.',
        'Tiempo fuera de jaula: asegurar el cuarto. Sin ventiladores, ventanas abiertas o plantas toxicas.',
      ],
      tone: 'tip',
    },
  ],

  vocalizationGuide: {
    title: 'Referencia de Vocalizaciones',
    subtitle: 'Que significa cada sonido y cuando prestar atencion.',
    items: [
      {
        id: 'singing',
        name: 'Canto / Gorjeo',
        icon: '\u{1F3B6}',
        description: 'Secuencias melodicas complejas con modulacion de frecuencia.',
        sound: 'Continuo, patrones de tono variados de 5-30 segundos.',
        mood: 'Feliz, contento, socialmente activo.',
        action: 'Excelente senal! Tu periquito esta comodo y prospera.',
      },
      {
        id: 'chattering',
        name: 'Parloteo',
        icon: '\u{1F4AC}',
        description: 'Vocalizaciones cortas rapidas y repetitivas.',
        sound: 'Rafagas rapidas y ritmicas a volumen moderado.',
        mood: 'Activo, social, comunicandose.',
        action: 'Conducta de bandada normal. Puede estar "hablando" contigo o practicando.',
      },
      {
        id: 'contact_call',
        name: 'Llamado de Contacto',
        icon: '\u{1F4E2}',
        description: 'Chirrido breve y tonal para localizar companeros.',
        sound: 'Un chirrido corto, 2-4 kHz, repetido cada pocos segundos.',
        mood: 'Buscando conexion, ansiedad leve si no se responde.',
        action: 'Responde con un silbido. Necesitan saber que estas ahi.',
      },
      {
        id: 'alarm',
        name: 'Llamado de Alarma',
        icon: '\u{1F6A8}',
        description: 'Chillido fuerte, agudo, de banda ancha.',
        sound: 'Aspero, agudo, sobresaltante. Puede repetirse rapidamente.',
        mood: 'Asustado, percibiendo amenaza.',
        action: 'Revisa amenazas: depredadores, sombras, movimientos subitos, objetos desconocidos.',
      },
      {
        id: 'distress',
        name: 'Llamado de Auxilio',
        icon: '\u{1F198}',
        description: 'Vocalizaciones irregulares y urgentes con alta energia.',
        sound: 'Tono variable, volumen alto, patron agitado.',
        mood: 'Dolor, estres extremo o incomodidad fisica.',
        action: 'Inspeccionar inmediatamente. Buscar heridas, enredos o signos de enfermedad.',
      },
      {
        id: 'beak_grinding',
        name: 'Rechinido de Pico',
        icon: '\u{1F634}',
        description: 'Sonido ritmico suave de frotamiento del pico.',
        sound: 'Baja amplitud, ritmo de 10-20 Hz, apenas audible.',
        mood: 'Profundamente relajado, somnoliento, contento.',
        action: 'Excelente senal! Tu periquito se siente seguro. Generalmente antes de dormir.',
      },
      {
        id: 'silence',
        name: 'Silencio Prolongado',
        icon: '\u{1F910}',
        description: 'Ausencia de vocalizaciones por periodos extendidos.',
        sound: 'Sin vocalizacion durante horas normalmente activas.',
        mood: 'Puede indicar enfermedad, miedo o depresion.',
        action: 'Si dura >2 horas en tiempo activo, revisar signos de salud. Consultar veterinario si hay otros sintomas.',
      },
    ],
  },

  healthChecklist: {
    title: 'Chequeo Rapido de Salud',
    subtitle: 'Recorre esta lista durante tu observacion diaria.',
    items: [
      {
        id: 'eyes',
        icon: '\u{1F441}',
        label: 'Ojos',
        healthy: 'Brillantes, claros, alertas, pupilas iguales.',
        warning: 'Hinchados, con costra, secrecion, semicerrados de dia.',
      },
      {
        id: 'cere',
        icon: '\u{1F535}',
        label: 'Cera (nariz)',
        healthy: 'Lisa, color consistente (azul=macho, marron/beige=hembra).',
        warning: 'Con costra, escamosa, descolorida o hinchada.',
      },
      {
        id: 'feathers',
        icon: '\u{1FAB6}',
        label: 'Plumas',
        healthy: 'Lisas, sedosas, bien acicaladas. Muda normal es gradual.',
        warning: 'Erizadas constantemente, parches calvos, barras de estres, ejes rotos.',
      },
      {
        id: 'breathing',
        icon: '\u{1F4A8}',
        label: 'Respiracion',
        healthy: 'Silenciosa, sin esfuerzo visible, cola quieta.',
        warning: 'Respiracion con boca abierta, cola moviendose, clics/silbidos.',
      },
      {
        id: 'droppings',
        icon: '\u{1F4A9}',
        label: 'Heces',
        healthy: 'Verde/blanco, firmes, consistentes. 40-50 al dia es normal.',
        warning: 'Acuosas, descoloridas (amarillo/negro/rojo), semillas sin digerir.',
      },
      {
        id: 'posture',
        icon: '\u{1F9CD}',
        label: 'Postura',
        healthy: 'Erguido, activo, una pata recogida al descansar.',
        warning: 'Sentado en el piso de jaula, encorvado, inflado de dia.',
      },
      {
        id: 'appetite',
        icon: '\u{1F37D}',
        label: 'Apetito',
        healthy: 'Comiendo regularmente, activo en comedero, abriendo semillas.',
        warning: 'Sentado en comedero sin comer, perdida de peso, comida sin tocar.',
      },
    ],
  },

  emergencySigns: {
    title: 'Emergencia: Ir al Veterinario Ya',
    subtitle: 'Estos signos requieren atencion veterinaria aviar urgente.',
    signs: [
      'Sentado en el piso de la jaula, inflado, ojos cerrados.',
      'Sangrado que no se detiene en 5 minutos.',
      'Respiracion con boca abierta o movimiento persistente de cola.',
      'Convulsiones, perdida de equilibrio o incapacidad de posarse.',
      'Vomito (sacudiendo cabeza + regurgitacion en plumas del pecho).',
      'Hinchazon subita en cualquier parte del cuerpo.',
      'Sin heces por mas de 12 horas.',
      'Ingestion de sustancia toxica (vapores de Teflon, chocolate, aguacate).',
    ],
    action:
      'Mantener al ave caliente (29\u00B0C), en un espacio oscuro y tranquilo, y transportar al veterinario aviar lo antes posible. No intentar tratamiento casero para estos sintomas.',
  },

  howToTitle: 'Como Usar Esta App Efectivamente',
  howToSteps: [
    '1. Agrega el perfil de cada periquito con nombre, foto y notas sobre su personalidad.',
    '2. Graba al menos 30 segundos de audio en un cuarto silencioso con el telefono cerca de la jaula.',
    '3. Revisa el analisis de IA: animo, tipo de vocalizacion, confianza y desglose de probabilidades.',
    '4. Verifica la insignia de deteccion de ave \u2014 si no se detecto, intenta un ambiente mas silencioso.',
    '5. Rastrea tendencias semanalmente en Historial. Una mala lectura no significa problema \u2014 busca patrones.',
    '6. Configura coordenadas del habitat en Ajustes para alertas de clima y calidad de aire.',
    '7. Usa esta Guia como referencia cuando notes cambios de conducta.',
  ],

  safetyNote:
    'Esta app ofrece monitoreo de bienestar con IA y contenido educativo. NO reemplaza el diagnostico profesional de un veterinario aviar calificado. En caso de duda, siempre consulta un veterinario.',
};
